file separati
franchiStud/PhoneBook pull request #1
Opened 2022-07-06 14:52 UTC by franchiStud

2022-07-07 16:27 UTC, lucaotta requested changes
Bene! Ti ho lasciato alcuni piccoli commenti, vedi se ti tornano.

2022-07-07 16:27 UTC, lucaotta commented on phoneBook.cpp
> +            return NULL;
```suggestion
            return nullptr;
```

2022-07-07 16:27 UTC, lucaotta commented on phoneBook.cpp
> +            for(int i=0;i<contacts.size();i++){
Visto che devi andare su tutti i contatti, usa il range-for o ancora meglio `std::for_each()`.
Il range-for è questo:
```c++
for (const auto &c : contacts)
```

2022-07-07 16:27 UTC, lucaotta commented on filter.h
> +        void initialize(std::vector<Contact> c);
Non ho capito a cosa ti serve `initialize()` in questa API e perché tu abbia bisogno di una copia dei contatti.

2022-07-07 16:27 UTC, lucaotta commented on filter.h
> +class filter {
Ma questa classe è solo un'interfaccia? Se sì, mi sembra strano che ci siano metodi virtuali non puri, costruttori e membri...

2022-07-07 16:27 UTC, lucaotta commented on main.cpp
> +            return count++ >= basevector.size()-2;
Personalmente non sono un fan degli operatori `++` e `--`, soprattutto se usati all'interno di un'espressione più complessa...

2022-07-08 09:05 UTC, franchiStud commented on filter.h
> +        void initialize(std::vector<Contact> c);
l'ho messo perché per alcuni filtri potrebbe essere necessario sapere il numero totale di contatti o simili (come in un filtro tipo "gli ultimi 2 elementi")
per evitare di creare una funzione propria delle sottoclassi e quindi dover modificare la stessa classe phonebook l'ho messo come metodo per tutti i filtri, anche se non tutti lo usano

2022-07-08 15:03 UTC, lucaotta approved these changes
Piccoli fix qua e là ma ci siamo! Ottimo lavoro!

2022-07-08 15:03 UTC, lucaotta commented on phoneBook.h
> +        virtual Contact* find(string n);
Lo vedo adesso: c'è un motivo particolare per cui hai fatto tutti i metodi di `PhoneBook` virtual?

2022-07-08 15:03 UTC, lucaotta commented on phoneBook.cpp
> +    for(int i=0;i<contacts.size();i++) {
Ti sei perso un range-for?

2022-07-08 15:03 UTC, lucaotta commented on phoneBook.cpp
> +Contact* PhoneBook:: find(string n){
Hai uno spazio di troppo tra `PhoneBook::` e `find`

2022-07-08 15:03 UTC, lucaotta commented on main.cpp
> +    vector<Contact> filtred = a.filterContacts(new last2Numbers(a.size()));
Typo
```suggestion
    vector<Contact> filtered = a.filterContacts(new last2Numbers(a.size()));
```

2022-07-12 13:52 UTC, lucaotta commented
Ok per me, mergia pure @franchiStud

2022-07-12 14:13 UTC, merged